{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: todo-chatbot
    component: backend
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  COHERE_API_KEY: {{ .Values.secrets.cohereApiKey | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
{{- end }}
